[build.environment]
  NPM_FLAGS = "--version"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm i --frozen-lockfile && npm run deploy"
