[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm install --no-frozen-lockfile && pnpm -w run deploy"

[functions]
  node_bundler = "esbuild"
