[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "16"

[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm@7.5.0 i --frozen-lockfile false && && pnpm -w run deploy"

[functions]
  node_bundler = "esbuild"
